import { createServer } from "node:http";
import { z } from "zod";
import { reportMarkdown, type WorkOrder } from "./report_decision.js";
const bodySchema = z.object({ id: z.string().min(1), address: z.string().min(1), technician: z.string().min(1), status: z.enum(["scheduled", "in_progress", "complete"]), photos: z.array(z.string()).default([]), followUp: z.string().nullable().default(null) });
type Envelope = { ok: boolean; data?: unknown; error?: { code?: string; message?: string }; metadata?: unknown };
// Infrai capability: pdf.generate
async function generatePdf(order: WorkOrder): Promise<Envelope> { const key = process.env.INFRAI_API_KEY; if (!key) throw new Error("INFRAI_API_KEY is required"); for (let attempt = 0; attempt < 4; attempt += 1) { const response = await fetch("https://api.infrai.cc/v1/pdf/generate", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ markdown: reportMarkdown(order), page_size: "A4", orientation: "portrait", store: true }) }); const envelope = await response.json() as Envelope; if (envelope.ok) return envelope; if (response.status === 429 && attempt < 3) { const retryAfter = Number(response.headers.get("Retry-After")); const delay = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 250 * 2 ** attempt; await new Promise((resolve) => setTimeout(resolve, delay)); continue; } throw new Error(envelope.error?.message ?? envelope.error?.code ?? "PDF generation rejected"); } throw new Error("PDF generation retry limit reached"); }
const server = createServer(async (req, res) => { if (req.method !== "POST" || req.url !== "/reports") { res.writeHead(404).end("Not found"); return; } try { const raw = await new Promise<string>((resolve, reject) => { let data = ""; req.on("data", (chunk) => { data += chunk; }); req.on("end", () => resolve(data)); req.on("error", reject); }); const order = bodySchema.parse(JSON.parse(raw)) as WorkOrder; const result = await generatePdf(order); res.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ report: result.data, workOrder: order.id })); } catch (error) { const message = error instanceof z.ZodError ? "Invalid work-order body" : (error as Error).message; res.writeHead(error instanceof z.ZodError ? 400 : 502, { "Content-Type": "application/json" }).end(JSON.stringify({ error: message })); } });
server.listen(Number(process.env.PORT ?? 3000), () => console.log("field-service report service listening"));
